// <auto-generated />
using Barinak.Odev.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Barinak.Odev.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20230805014148_4")]
    partial class _4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Barinak.Odev.Models.Hayvanlar", b =>
                {
                    b.Property<int>("hayid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("hayid"));

                    b.Property<int>("Turlerturid")
                        .HasColumnType("int");

                    b.Property<string>("ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sahiplenmeDurum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sehir")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("turid")
                        .HasColumnType("int");

                    b.Property<int>("yas")
                        .HasColumnType("int");

                    b.HasKey("hayid");

                    b.HasIndex("Turlerturid");

                    b.ToTable("Hayvanlars");
                });

            modelBuilder.Entity("Barinak.Odev.Models.Turler", b =>
                {
                    b.Property<int>("turid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("turid"));

                    b.Property<string>("turler")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("turid");

                    b.ToTable("Turlers");
                });

            modelBuilder.Entity("Barinak.Odev.Models.Hayvanlar", b =>
                {
                    b.HasOne("Barinak.Odev.Models.Turler", "Turler")
                        .WithMany("Hayvanlars")
                        .HasForeignKey("Turlerturid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Turler");
                });

            modelBuilder.Entity("Barinak.Odev.Models.Turler", b =>
                {
                    b.Navigation("Hayvanlars");
                });
#pragma warning restore 612, 618
        }
    }
}
